services:
  app:
    build: .
    ports:
      - "1111:1111"
    depends_on:
      - mongodb
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - 27017:27017
    logging:
      driver: none
